server:
  port: 8080

logging:
  level:
    root: info
    org.cent.demo.mapper: trace

#spring:
#  datasource:
#    name: mytest
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mytest?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 123456

spring:
  datasource:
    # 数据源JDBC基本配置
    name: mytest
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db-url}
    username: ${db-user}
    password: ${db-password}
#    # HikariCP连接池配置
#    # 数据源类型，spring boot 2.0+, 默认HikariCP数据源
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      pool-name: DatebookHikariCP
#      minimum-idle: 5
#      maximum-pool-size: 15
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#      validation-timeout: 60000

    # druid连接池配置
    # 数据源类型，可使用非默认HikariCP数据源，如阿里巴巴druid，内置强大的监控功能
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接初始值，连接池启动时创建的连接数量的初始值
      initial-size: 5
      # 最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
      min-idle: 5
      # 连接池的最大值，同一时间可以从池分配的最多连接数量，0时无限制
      max-active: 20
      # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
      # 配置了max-wait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置use-unfair-lock属性为true使用非公平锁
      max-wait: 60000
      # 是否缓存PreparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，pool-prepared-statements自动触发修改为true。
      # 在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
      # 增加对连接池中连接的测试/验证，防止数据库认为连接已死而Web应用服务器认为连接还有效的问题
      # MYSQL : SELECT 1
      # ORACLE: SELECT 1 FROM DUAL
      # Microsoft SQL: SELECT 1
      validation-query: SELECT 1 FROM DUAL
      # 检测超时
      validation-query-timeout: 60000
      # 申请连接时执行validation-query检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: true
      # 归还连接时执行validation-query检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
      # 如果空闲时间大于time-between-eviction-runs-millis，执行validation-query检测连接是否有效
      test-while-idle: true
      # 连接池中的min-idle数量以内的连接，空闲时间超过min-evictable-idle-time-millis，则会执行keep-alive操作
      keep-alive: false
      # 有两个含义：
      # 1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于min-evictable-idle-time-millis则关闭物理连接
      # 2) test-while-idle的判断依据，详细看test-while-idle属性的说明
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 300000

      # 监控配置
      # 通过别名的方式配置扩展插件，常用的插件有：
      # 监控统计用的filter:stat
      # 日志用的filter:log4j2，(log4j、log4j2、slf4j、commonLogging)
      # 防御sql注入的filter:wall
      filters: stat,wall,log4j2
      # 通过connect-properties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

      # WebStatFilter配置，用于采集web-jdbc关联监控的数据
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      # StatViewServlet配置
      stat-view-servlet:
        # 启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        # 白名单，默认空允许所有访问
        allow: 127.0.0.1
        # 黑名单，与白名单存在共同时，deny优先于allow
        deny: ""

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  type-aliases-package: org.cent.demo.domain

# spring actuator 应用监控（健康探测）
management:
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
    redis:
      enabled: true
  endpoint:
    health:
      # never：默认配置，不展示详细信息，up或者down的状态
      # when-authorized：详细信息将会展示给通过认证的用户。授权的角色可以通过
      # always：暴露详细信息
      show-details: always