server:
  port: 8080

spring:
  datasource:
    name: mytest
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db-url}
    username: ${db-user}
    password: ${db-password}

#spring:
#  datasource:
#    name: mytest
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mytest?serverTimezone=UTC&useSSL=false
#    username: root
#    password: 123456
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  type-aliases-package: org.cent.demo.domain